// Scripted model, real installed native Agent tools, storage and Excalidraw history.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {prepareHost,hostContext,editorFrame,installEditorInspection} from './fixtures/browser-session.mjs';
const url=process.env.DSH_SMOKE_URL;if(!url)throw new Error('Isolated DSH profile URL required');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium',args:['--no-sandbox']});
let page;
try{
 const ctx=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true});await ctx.addInitScript(installEditorInspection);
 page=await ctx.newPage();page.setDefaultTimeout(25000);const errors=[];let matched=false,analysis=0;
 const source=await readFile('lib/client.js','utf8');page.on('response',async r=>{if(new URL(r.url()).pathname.startsWith('/plugins/')&&(await r.text().catch(()=>'')).includes(source))matched=true;});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/advice/generate'))analysis++;});
 await prepareHost(page,url);assert(matched);await hostContext(page,'create',process.cwd());
 const input=page.locator('[contenteditable=true]'),button=page.getByRole('button',{name:'打开手绘参考板'});await input.fill('保留编辑上下文');await button.click();let frame=await editorFrame(page);
 const ready=()=>frame.waitForFunction(()=>{try{return !!window.__sketchEditor();}catch{return false;}});await ready();
 const call=(method,owner,payload)=>frame.evaluate(async args=>{const r=await fetch('/sketch-reference-rpc/v1/'+args.method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({protocolVersion:1,requestId:crypto.randomUUID(),owner:args.owner,payload:args.payload})});const b=await r.json();if(!b.ok)throw new Error(b.error.code);return b.value;},{method,owner,payload});
 const load=()=>call('drawing/get',null,{sessionId:new URL(frame.url()).searchParams.get('sessionId')});
 const stats=()=>page.evaluate(async()=>{const r=await fetch('/sketch-reference-test-agent-stats');return r.json();});
 await frame.evaluate(()=>{const base={x:100,y:100,width:100,height:80,angle:0,strokeColor:'#1e1e1e',backgroundColor:'transparent',fillStyle:'solid',strokeWidth:1,strokeStyle:'solid',roughness:1,opacity:100,groupIds:[],frameId:null,roundness:null,seed:1,isDeleted:false,boundElements:null,updated:1,link:null,locked:false,version:1,versionNonce:1};window.__sketchEditor().updateScene({elements:[{...base,id:'edit-rect',type:'rectangle'},{...base,id:'edit-delete',type:'ellipse',x:280}],captureUpdate:'NEVER'});});
 await frame.getByLabel('这张图准备用来做什么？').fill('通用结构讨论');await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();const initial=await load();
 const propose=async()=>{const before=(await stats()).calls.length,previousId=(await call('proposal/get',initial.owner,null)).proposal?.id,replyCount=await page.getByText('SKETCH_EDIT_DONE：修改提议已保存，等待用户确认。',{exact:true}).count();await input.fill('SKETCH_AGENT_TEST PROPOSE：提出修改，等待我确认。');await input.press('Enter');await page.getByText('SKETCH_EDIT_DONE：修改提议已保存，等待用户确认。',{exact:true}).nth(replyCount).waitFor();const p=await call('proposal/get',initial.owner,null);assert(p.proposal);assert.notEqual(p.proposal.id,previousId);await frame.getByText('待确认',{exact:true}).waitFor();await frame.getByRole('button',{name:'修改提议 ⌄',exact:true}).waitFor();assert((await stats()).calls.slice(before).some(c=>c.tools.includes('sketch_propose_edit')));return p.proposal;};
 const first=await propose();assert.equal((await load()).drawing.revision,initial.drawing.revision,'A native proposal must not edit before confirmation');
 await frame.getByRole('button',{name:'修改提议 ⌄',exact:true}).click();assert.equal(await frame.getByRole('button',{name:'确认应用修改',exact:true}).count(),0);
 await frame.getByRole('button',{name:'预览修改',exact:true}).click();await frame.getByRole('img',{name:'修改后的草图预览（尚未应用）'}).waitFor();assert.equal((await load()).drawing.revision,first.baseRevision);
 await frame.getByLabel('这张图准备用来做什么？').fill('用户已修改用途');await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();const changed=await load();
 await frame.getByRole('button',{name:'确认应用修改',exact:true}).click();await frame.getByRole('alert').filter({hasText:'草图已变化，请重新提议'}).waitFor();assert.equal((await load()).drawing.revision,changed.drawing.revision);
 const second=await propose();await frame.getByRole('button',{name:'修改提议 ⌄',exact:true}).click();await frame.getByRole('button',{name:'预览修改',exact:true}).click();await frame.getByRole('img',{name:'修改后的草图预览（尚未应用）'}).waitFor();
 const beforeCalls=(await stats()).calls.length;
 await frame.getByRole('button',{name:'确认应用修改',exact:true}).click();await frame.getByRole('alert').filter({hasText:'修改已应用并保存'}).waitFor();
 await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();const applied=await load();assert.equal(applied.drawing.scene.elements.length,6);assert(!applied.drawing.scene.elements.some(e=>e.id==='edit-delete'));assert.equal(applied.drawing.scene.elements.find(e=>e.id==='edit-rect').x,150);assert.equal(applied.drawing.scene.elements.find(e=>e.id==='edit-rect').width,200);assert(applied.drawing.scene.elements.some(e=>e.text==='Agent 中文文字'));assert.equal((await call('proposal/get',initial.owner,null)).proposal.status,'applied');assert.equal((await stats()).calls.length,beforeCalls,'Preview/apply must not call a model');
 // Native undo: one captured edit restores the complete before scene.
 await frame.getByRole('button',{name:'修改提议 ⌃',exact:true}).click();await frame.locator('.excalidraw canvas.interactive').click({position:{x:650,y:400}});await page.keyboard.press('Control+z');
 await frame.waitForFunction(()=>window.__sketchEditor().getSceneElements().length===2);await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();const undone=await load();assert.equal(undone.drawing.scene.elements.find(e=>e.id==='edit-rect').x,100);assert(undone.drawing.scene.elements.some(e=>e.id==='edit-delete'));
 const third=await propose();await frame.getByRole('button',{name:'修改提议 ⌄',exact:true}).click();await frame.getByRole('button',{name:'预览修改',exact:true}).click();await frame.getByRole('img',{name:'修改后的草图预览（尚未应用）'}).waitFor();
 let attempts=0,committedRevision;const lost=async route=>{if(++attempts===1){const response=await route.fetch();const body=await response.json();assert(body.ok);committedRevision=body.value.revision;const request=route.request().postDataJSON();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,requestId:request.requestId,error:{code:'TEST_LOST_ACK',message:'测试：应用成功后响应丢失'}})});}else await route.continue();};
 await page.route('**/proposal/apply',lost);await frame.getByRole('button',{name:'确认应用修改',exact:true}).click();await frame.getByRole('button',{name:'重试确认修改',exact:true}).waitFor();
 await frame.getByRole('button',{name:'返回聊天 ×'}).click();await frame.getByRole('alert').filter({hasText:'修改结果尚未确认，请重试'}).waitFor();
 await frame.getByRole('button',{name:'重试确认修改',exact:true}).click();await frame.getByRole('alert').filter({hasText:'修改已应用并保存'}).waitFor();await page.unroute('**/proposal/apply',lost);assert.equal(attempts,2);assert.equal((await load()).drawing.revision,committedRevision);assert.equal((await call('proposal/get',initial.owner,null)).proposal.id,third.id);
 const downloading=page.waitForEvent('download');await frame.getByRole('button',{name:'下载修改前草稿',exact:true}).click();const backup=await downloading;await mkdir('test-results',{recursive:true});await backup.saveAs('test-results/edit-before.excalidraw');assert.deepEqual(JSON.parse(await readFile('test-results/edit-before.excalidraw','utf8')).elements,third.before.elements);
 await frame.getByRole('button',{name:'返回聊天 ×'}).click();await page.locator('iframe[title="手绘参考板"]').waitFor({state:'detached'});await input.fill('原输入仍可继续');await button.click();frame=await editorFrame(page);await ready();assert.equal((await call('proposal/get',initial.owner,null)).proposal.status,'applied');assert.equal((await load()).drawing.scene.elements.length,6);
 await hostContext(page,'create',process.cwd());await button.click();frame=await editorFrame(page);await ready();const other=await load();assert.equal((await call('proposal/get',other.owner,null)).proposal,null);
 await hostContext(page,'open',initial.owner.sessionId);frame=await editorFrame(page);await ready();assert.equal((await call('proposal/get',initial.owner,null)).proposal.id,third.id);
 const fourth=await propose();await frame.getByRole('button',{name:'修改提议 ⌄',exact:true}).click();await frame.getByRole('button',{name:'忽略提议',exact:true}).click();await frame.getByText('已忽略',{exact:true}).waitFor();assert.equal((await call('proposal/get',initial.owner,null)).proposal.id,fourth.id);
 assert.equal(analysis,0);assert.deepEqual(errors,[]);await mkdir('test-results',{recursive:true});await writeFile('test-results/edits-session.json',JSON.stringify({owner:initial.owner,proposal:(await call('proposal/get',initial.owner,null)).proposal,drawing:(await load()).drawing}));await page.screenshot({path:'test-results/edits.png'});
 console.log('PASS: real native propose tool with scripted model, no edits before preview/confirmation, stale rejection, native shape/text/arrow create/move/resize/delete, one-step undo and autosave, lost-ACK retry/close protection, close/reopen, exact-session isolation, ignore and zero independent analysis calls.');
}catch(e){if(page){await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/edits-failure.png'}).catch(()=>{});const frames=page.frames();for(const f of frames)if(f.url().includes('sketch-reference-assets')){console.log('Editor diagnostic:',await f.locator('body').innerText().catch(()=>''));console.log('Synthetic scene diagnostic:',await f.evaluate(()=>window.__sketchEditor().getSceneElements().map(e=>({id:e.id,type:e.type,x:e.x,y:e.y}))).catch(()=>null));}}throw e;}finally{await browser.close();}
