// Native DSH image tool + actual attachment bytes/Excalidraw. Scripted model only.
import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {prepareHost,hostContext,editorFrame,installEditorInspection} from './fixtures/browser-session.mjs';
const url=process.env.DSH_SMOKE_URL;if(!url)throw new Error('Isolated installed DSH URL required');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium',args:['--no-sandbox']});let page;
try{
 const context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true});await context.addInitScript(installEditorInspection);page=await context.newPage();page.setDefaultTimeout(25000);const errors=[];let advice=0,matched=false;
 const client=await readFile('lib/client.js','utf8');page.on('response',async r=>{if(new URL(r.url()).pathname.startsWith('/plugins/')&&(await r.text().catch(()=>'')).includes(client))matched=true;});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/advice/generate'))advice++;});
 await prepareHost(page,url);assert(matched);await hostContext(page,'create',process.cwd());const input=page.locator('[contenteditable=true]'),button=page.getByRole('button',{name:'打开手绘参考板'});await input.fill('准备图片时保留此输入');await button.click();let frame=await editorFrame(page);
 const ready=()=>frame.waitForFunction(()=>{try{return !!window.__sketchEditor();}catch{return false;}});await ready();
 const call=(method,owner,payload)=>page.evaluate(async args=>{const r=await fetch('/sketch-reference-rpc/v1/'+args.method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({protocolVersion:1,requestId:crypto.randomUUID(),owner:args.owner,payload:args.payload})});const b=await r.json();if(!b.ok)throw new Error(b.error.code);return b.value;},{method,owner,payload});
 const load=()=>call('drawing/get',null,{sessionId:new URL(frame.url()).searchParams.get('sessionId')});const stats=()=>page.evaluate(async()=>{const r=await fetch('/sketch-reference-test-agent-stats');return r.json();});
 await frame.evaluate(()=>{const base={x:100,y:100,width:100,height:80,angle:0,strokeColor:'#1e1e1e',backgroundColor:'transparent',fillStyle:'solid',strokeWidth:1,strokeStyle:'solid',roughness:1,opacity:100,groupIds:[],frameId:null,roundness:null,seed:1,isDeleted:false,boundElements:null,updated:1,link:null,locked:false,version:1,versionNonce:1};window.__sketchEditor().updateScene({elements:[{...base,id:'visual-r',type:'rectangle'},{...base,id:'visual-free',type:'freedraw',x:700,width:80,points:[[0,0],[80,0],[40,80],[0,0]],pressures:[],simulatePressure:true}],captureUpdate:'NEVER'});});
 await frame.getByLabel('这张图准备用来做什么？').fill('通用自由手绘讨论');await expect.poll(async()=>(await load()).drawing?.scene.elements.length).toBe(2);await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();const initial=await load();
 const menu=async name=>{await frame.getByRole('button',{name:'更多操作',exact:true}).click();await frame.getByRole('button',{name,exact:true}).click();};
 const ask=async(task,answer)=>{const count=await page.getByText(answer,{exact:true}).count();await input.fill('SKETCH_AGENT_TEST '+task);await input.press('Enter');await page.getByText(answer,{exact:true}).nth(count).waitFor();};
 await ask('READ_VISUAL：读取尚未准备的图片。','SKETCH_VISUAL_REFUSED：图片读取失败，未修改草图。');assert.equal((await load()).drawing.revision,initial.drawing.revision);
 await input.fill('更新图片不能自动发送或改写此输入');const before=await stats(),rasterizations=await frame.evaluate(()=>window.__sketchMetrics.rasterizations);
 await menu('更新视觉参考');await frame.getByRole('alert').filter({hasText:'视觉参考已更新'}).waitFor();const prepared=await call('visual/get',initial.owner,null);assert.equal(prepared.all.revision,initial.drawing.revision);assert.equal(prepared.all.stale,false);assert((await input.innerText()).includes('不能自动发送'));assert.equal((await stats()).calls.length,before.calls.length);assert.equal((await load()).drawing.revision,initial.drawing.revision);
 await menu('更新视觉参考');await frame.getByRole('alert').filter({hasText:'视觉参考已更新'}).waitFor();assert.equal((await stats()).imageSaves,before.imageSaves+1);assert.equal((await frame.evaluate(()=>window.__sketchMetrics.rasterizations))-rasterizations,1);
 for(const height of [480,360]){
  await page.setViewportSize({width:900,height});await frame.getByRole('button',{name:'更多操作',exact:true}).click();
  const bounds=await frame.locator('.moreMenu').evaluate(n=>({top:n.getBoundingClientRect().top,bottom:n.getBoundingClientRect().bottom,height:innerHeight,scrollable:n.scrollHeight>n.clientHeight}));assert(bounds.top>=0&&bounds.bottom<=bounds.height,JSON.stringify(bounds));if(height===360)assert(bounds.scrollable,JSON.stringify(bounds));
  await frame.getByRole('button',{name:'草稿备份',exact:true}).scrollIntoViewIfNeeded();await frame.getByRole('button',{name:'更新视觉参考',exact:true}).scrollIntoViewIfNeeded();await frame.getByRole('button',{name:'更多操作',exact:true}).click();
 }
 await page.setViewportSize({width:1600,height:1000});assert.equal((await load()).drawing.revision,initial.drawing.revision);
 await frame.evaluate(()=>window.__sketchEditor().updateScene({appState:{selectedElementIds:{'visual-r':true}},captureUpdate:'NEVER'}));await menu('选区作为重点');await frame.getByRole('alert').filter({hasText:'选区重点已设置'}).waitFor();await menu('更新重点视觉参考');await frame.getByRole('alert').filter({hasText:'重点视觉参考已更新'}).waitFor();const focused=await call('visual/get',initial.owner,null);assert.deepEqual(focused.selection.elementIds,['visual-r']);assert(focused.focus.width<focused.all.width);
 await ask('READ_VISUAL FOCUS_VISUAL：只读取重点图片。','SKETCH_VISUAL_DONE：focus 原生图片可见，未修改草图。');
 await frame.getByRole('button',{name:'返回聊天 ×'}).click();await page.locator('iframe[title="手绘参考板"]').waitFor({state:'detached'});await ask('READ_VISUAL：画板关闭后读取全图。','SKETCH_VISUAL_DONE：all 原生图片可见，未修改草图。');assert((await stats()).calls.some(c=>c.task.includes('READ_VISUAL')&&c.toolImages?.length));
 await button.click();frame=await editorFrame(page);await ready();await frame.getByLabel('这张图准备用来做什么？').fill('修改用途后旧图需要更新');await expect.poll(async()=>(await load()).drawing.goal).toBe('修改用途后旧图需要更新');await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();const changed=await load();assert((await call('visual/get',initial.owner,null)).all.stale);await frame.getByLabel('协作状态').filter({hasText:'视觉参考待更新'}).waitFor();
 await ask('READ_VISUAL：不要把旧图片作为当前版本。','SKETCH_VISUAL_REFUSED：图片读取失败，未修改草图。');assert.equal((await load()).drawing.revision,changed.drawing.revision);
 let attempts=0;const lose=async route=>{if(++attempts===1){const response=await route.fetch();assert((await response.json()).ok);const body=route.request().postDataJSON();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,requestId:body.requestId,error:{code:'TEST_LOST_ACK',message:'测试：图片保存后响应丢失'}})});}else await route.continue();};await page.route('**/visual/prepare',lose);
 const writes=(await stats()).imageSaves;await menu('更新视觉参考');await frame.getByRole('alert').filter({hasText:'图片保存后响应丢失'}).waitFor();await menu('更新视觉参考');await frame.getByRole('alert').filter({hasText:'视觉参考已更新'}).waitFor();await page.unroute('**/visual/prepare',lose);assert.equal(attempts,2);assert.equal((await stats()).imageSaves,writes+1);assert.equal((await load()).drawing.revision,changed.drawing.revision);
 await assert.rejects(call('visual/prepare',initial.owner,{revision:changed.drawing.revision,pngBase64:'not-png'}),/INVALID_PNG/);await assert.rejects(call('visual/prepare',initial.owner,{revision:initial.drawing.revision,pngBase64:'AQ=='}),/REVISION_CONFLICT/);
 const saved=await call('visual/get',initial.owner,null);await hostContext(page,'create',process.cwd());await page.locator('iframe[title="手绘参考板"]').waitFor({state:'detached'});const otherId=await hostContext(page,'create',process.cwd()),other=await call('drawing/get',null,{sessionId:otherId});assert.equal((await call('visual/get',other.owner,null)).all,null);
 await assert.rejects(call('visual/get',{...initial.owner,cwd:'/other'},null),/SESSION_CHANGED/);assert.equal((await call('drawing/get',initial.owner,{sessionId:initial.owner.sessionId})).drawing.revision,changed.drawing.revision);
 assert.equal(advice,0);assert.deepEqual(errors,[]);await mkdir('test-results',{recursive:true});await writeFile('test-results/visual-session.json',JSON.stringify({owner:initial.owner,revision:changed.drawing.revision,state:saved}));await writeFile('test-results/visual-native.json',JSON.stringify({realModel:false,inputTokens:null,calls:(await stats()).calls.slice(before.calls.length),errors}));await page.screenshot({path:'test-results/visual.png'});
 console.log('PASS: explicit native PNG preparation without model/drawing/input writes, cached export/admission, selected PNG, real native tool image block with board closed, missing/stale rejection, lost-ACK reuse, version/lifecycle isolation. Scripted model only.');
}catch(e){if(page){await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/visual-failure.png'}).catch(()=>{});console.log('Visual test diagnostic:',await page.locator('body').innerText().then(s=>s.slice(-2000)).catch(()=>''));}throw e;}finally{await browser.close();}
