// Installed DSH + real Agent loop + Excalidraw. Model responses are scripted.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {prepareHost,hostContext,editorFrame,installEditorInspection} from './fixtures/browser-session.mjs';
const url=process.env.DSH_SMOKE_URL;if(!url)throw new Error('Dedicated DSH URL with mock-native-agent.overlay.yml required');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium',args:['--no-sandbox']});
let page;const report={fixture:'scripted model; real installed DSH native Agent/tool execution',realModel:false,inputTokens:null};
try{
 const context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true});await context.addInitScript(installEditorInspection);
 page=await context.newPage();page.setDefaultTimeout(20000);const errors=[];let analysisRequests=0,clientVerified=false;
 const installedClient=await readFile(process.env.DSH_PERF_CLIENT??'lib/client.js','utf8');page.on('response',async response=>{if(new URL(response.url()).pathname.startsWith('/plugins/')){const source=await response.text().catch(()=>null);if(source?.includes(installedClient))clientVerified=true;}});
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/advice/generate'))analysisRequests++;});
 await prepareHost(page,url);
 assert(clientVerified,'Browser must execute the installed client artifact');report.installedClientMatched=true;
 await hostContext(page,'create',process.cwd());
 const stats=()=>page.evaluate(async()=>{const response=await fetch('/sketch-reference-test-agent-stats');if(!response.ok)throw new Error('Native fixture missing');return response.json();});
 const baseline=(await stats()).calls.length;assert.deepEqual((await stats()).registered,[true,true]);
 const button=page.getByRole('button',{name:'打开手绘参考板'}),input=page.locator('[contenteditable=true]');await input.fill('原生输入保留');await button.click();let frame=await editorFrame(page);
 const ready=()=>frame.waitForFunction(()=>{try{return !!window.__sketchEditor();}catch{return false;}});await ready();
 const call=(method,owner,payload)=>frame.evaluate(async({method,owner,payload})=>{const r=await fetch(`/sketch-reference-rpc/v1/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({protocolVersion:1,requestId:crypto.randomUUID(),owner,payload})});const body=await r.json();if(!body.ok)throw new Error(body.error.code);return body.value;},{method,owner,payload});
 const load=()=>call('drawing/get',null,{sessionId:new URL(frame.url()).searchParams.get('sessionId')});
 await frame.evaluate(()=>{const base={x:120,y:160,width:180,height:100,angle:0,strokeColor:'#1e1e1e',backgroundColor:'transparent',fillStyle:'solid',strokeWidth:1,strokeStyle:'solid',roughness:1,opacity:100,groupIds:[],frameId:null,roundness:null,seed:1,isDeleted:false,boundElements:null,updated:1,link:null,locked:false,version:1,versionNonce:1};window.__sketchEditor().updateScene({elements:[{...base,id:'agent-rect',type:'rectangle'},{...base,id:'agent-free',type:'freedraw',x:400,y:160,width:90,height:100,points:[[0,0],[50,40],[90,100]],pressures:[],simulatePressure:true,lastCommittedPoint:null}]});});
 await frame.getByLabel('这张图准备用来做什么？').fill('讨论几何和自由手绘物品');await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();const first=await load();
 await frame.getByRole('button',{name:'作为参考发送',exact:true}).click();await frame.getByRole('alert').filter({hasText:'参考图已加入'}).waitFor();assert((await input.innerText()).includes('原生输入保留'));
 await input.fill('SKETCH_AGENT_TEST ANNOTATE：解释并标注草图。');await input.press('Enter');
 await page.getByText('SKETCH_AGENT_DONE：模拟原生回答与批注已完成。',{exact:true}).waitFor();
 await frame.locator('.commentMarker').first().waitFor();await frame.getByRole('button',{name:'展开建议与批注'}).click();await frame.getByRole('button',{name:'① 几何关系'}).click();
 assert.equal(await frame.getByRole('button',{name:'使用建议',exact:true}).count(),0);assert.equal(await frame.locator('.commentMarker').count(),2);
 const markers=await frame.locator('.commentMarker').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().left));assert(Math.abs(markers[0]-markers[1])>=28);
 await frame.getByRole('button',{name:'批注③',exact:true}).click();await frame.getByRole('dialog',{name:'批注详情③'}).waitFor();await frame.getByRole('button',{name:'① 几何关系',exact:true}).click();
 assert.equal((await load()).drawing.revision,first.drawing.revision);
 const agent=await call('agent/get',first.owner,null);assert.equal(agent.batch.advice.suggestions[0].anchor.elementId,'agent-rect');assert.equal(agent.batch.advice.suggestions[1].anchor,undefined);
 assert.equal((await stats()).calls.slice(baseline).some(c=>c.hasImage),true);
 assert.equal(analysisRequests,0,'Native Agent must not trigger independent advice');
 await frame.getByRole('button',{name:'AI 分析草图',exact:true}).click();await frame.getByText('模拟布局建议：用于协议与界面测试',{exact:true}).waitFor();
 assert((await load()).latestAdvice);assert.equal((await call('agent/get',first.owner,null)).batch.id,agent.batch.id);
 await frame.getByRole('button',{name:'Agent 批注',exact:true}).click();await frame.getByRole('button',{name:'① 几何关系',exact:true}).click();
 await frame.locator('.commentCard').first().getByRole('button',{name:'标记已解决'}).click();await frame.locator('.commentCard.resolved').waitFor();const solved=await call('agent/get',first.owner,null);assert.equal(solved.batch.comments[0].status,'resolved');
 await frame.getByRole('button',{name:'返回聊天 ×'}).click();await page.locator('iframe[title="手绘参考板"]').waitFor({state:'detached'});
 await page.waitForFunction(async()=>{const value=await (await fetch('/sketch-reference-test-agent-stats')).json();return value.eventClients===0;});
 await input.fill('SKETCH_AGENT_TEST READ_ONLY：读取已保存草图，不需要批注。');await input.press('Enter');await page.getByText('SKETCH_AGENT_READ_DONE：当前已保存 2 个元素，未创建批注。',{exact:true}).waitFor();
 await button.click();frame=await editorFrame(page);await ready();assert.equal((await call('agent/get',first.owner,null)).batch.id,agent.batch.id);await frame.getByRole('button',{name:'展开建议与批注'}).click();await frame.locator('.commentCard.resolved').waitFor();
 await frame.evaluate(()=>{const api=window.__sketchEditor();api.updateScene({elements:api.getSceneElements().map(e=>e.id==='agent-rect'?{...e,x:e.x+80,version:e.version+1}:e)});});await frame.getByText('较早版本',{exact:true}).waitFor();await frame.getByRole('status').filter({hasText:'已保存'}).waitFor();
 await frame.getByRole('button',{name:'更多操作',exact:true}).click();await Promise.all([page.waitForEvent('download'),frame.getByRole('button',{name:'导出 PNG',exact:true}).click()]);
 await hostContext(page,'create',process.cwd());await page.locator('iframe[title="手绘参考板"]').waitFor({state:'detached'});await button.click();frame=await editorFrame(page);await ready();const second=await load();assert.notEqual(second.owner.sessionId,first.owner.sessionId);assert.equal((await call('agent/get',second.owner,null)).batch,null);
 await hostContext(page,'open',first.owner.sessionId);frame=await editorFrame(page);await ready();assert.equal((await call('agent/get',first.owner,null)).batch.id,agent.batch.id);
 const protectedDrawing=(await load()).drawing;
 await input.fill('SKETCH_AGENT_TEST FAIL：模拟模型失败。');await input.press('Enter');await page.getByText('Synthetic native model failure',{exact:false}).first().waitFor();
 assert.equal((await load()).drawing.revision,protectedDrawing.revision);assert.equal((await call('agent/get',first.owner,null)).batch.id,agent.batch.id);
 await input.fill('SKETCH_AGENT_TEST CANCEL：模拟慢请求并取消。');await input.press('Enter');
 await page.waitForFunction(async()=>{const value=await (await fetch('/sketch-reference-test-agent-stats')).json();return value.calls.some(c=>c.task.includes('CANCEL'));});
 await page.getByRole('button',{name:/Stop/i}).first().click();
 await page.waitForFunction(async()=>{const value=await (await fetch('/sketch-reference-test-agent-stats')).json();return value.calls.findLast(c=>c.task.includes('CANCEL'))?.aborted===true;});
 assert.equal((await load()).drawing.revision,protectedDrawing.revision);
 await frame.getByRole('button',{name:'更多操作',exact:true}).click();await Promise.all([page.waitForEvent('download'),frame.getByRole('button',{name:'导出 PNG',exact:true}).click()]);
 await frame.getByRole('button',{name:'作为参考发送',exact:true}).click();await frame.getByRole('alert').filter({hasText:'参考图已加入'}).waitFor();
 const anonymous=await browser.newContext();assert.equal((await anonymous.request.get(new URL('/sketch-reference-events/v1',url).href)).status(),401);await anonymous.close();
 const metrics=await call('agent/metrics',first.owner,null);assert(metrics.measurements.some(m=>m.tool==='sketch_read'));assert(metrics.measurements.some(m=>m.tool==='sketch_annotate'));assert.equal(metrics.inputTokens,null);
 report.measurements=metrics.measurements;report.calls=(await stats()).calls.slice(baseline);report.analysisRequests=analysisRequests;report.errors=errors;
 assert.equal(analysisRequests,1,'Only the one explicit analysis may call advice');assert.deepEqual(errors,[]);await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/agent.png'});await writeFile('test-results/agent-native.json',JSON.stringify(report,null,2));
 await writeFile('test-results/agent-session.json',JSON.stringify({owner:first.owner,drawingRevision:protectedDrawing.revision,batch:(await call('agent/get',first.owner,null)).batch}));
 console.log('PASS: native Agent chat/tool loop (scripted model), PNG input, live anchored/global/stacked comments, independent legacy advice, status persistence, closed-board reads, stale comments, failure/cancel safety, export/reference, session isolation and event cleanup; one explicit analysis only.');
}catch(error){if(page){await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/agent-failure.png'}).catch(()=>{});console.log('Agent test diagnostic:',await page.locator('body').innerText().then(s=>s.slice(-2200)).catch(()=>''));}throw error;}finally{await browser.close();}
